#overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#point generic base configucation
resources: 
  - ../../base
#Automatically inject this namespace into all resources
namespace: dev-app
