apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app-test
  namespace: argocd
spec:
  destination:
    namespace: dev-app
    server: https://kubernetes.default.svc
  source:
    path: overlays/dev
    repoURL: https://github.com/rpkkashyap/nginx.git
    targetRevision: HEAD
  sources: []
  project: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: ture
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true  
      - RespectIgnoreDifferences=true
