apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app-test
  namespace: argocd
spec:
  destination:
    namespace: dev-app
    server: https://kubernetes.default.svc
  source:
    path: overlays/dev
    repoURL: https://github.com/rpkkashyap/nginx.git
    targetRevision: HEAD
  sources: []
  project: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true  
      - RespectIgnoreDifferences=true
  roles:
  - name: dev-developer-role
    description: "Developer access to dev-project"
    policies:
    - p, proj:dev-project:dev-developer-role, applications, get, dev-project/*, allow
    - p, proj:dev-project:dev-developer-role, applications, sync, dev-project/*, allow
    
    # --- Map the local user here ---
    groups:
    - account:test1  # Maps the local Argo CD user directly to this ro
